/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.bukuController;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import model.TableModelBuku;
import model.TblBuku;

/**
 *
 * @author User
 */
public class buku extends javax.swing.JFrame {

    /**
     * Creates new form buku
     */
    EntityManagerFactory emf = Persistence.createEntityManagerFactory("finalproject_team6PU");
    EntityManager em = emf.createEntityManager();
    bukuController bukujpa = new bukuController(em);
    List<TblBuku> list = new ArrayList<TblBuku>();
    private final TableModelBuku tableModelBuku;
    TblBuku buku = new TblBuku();
    
    public buku() {
        initComponents();
        tableModelBuku = new TableModelBuku();
        ButtonGroup group = new ButtonGroup();
        group.add(rbCariSemua);
        group.add(rbCariJudul);
        tblBuku.setModel(tableModelBuku);
        list = bukujpa.tampilSemua();
        for (TblBuku buku : list)
        {
            tableModelBuku.insert(buku);
        }
        txtKodeBuku.setEditable(false);
        idOtomatis();
    }
    
    private void refresh() {
        tableModelBuku.deleteall();
        list = bukujpa.tampilSemua();
        for (TblBuku buku : list) {
            tableModelBuku.insert(buku);
        }
        rbCariSemua.setSelected(false);
        rbCariJudul.setSelected(false);
        idOtomatis();
    }
    
    private void clear()
    {
        txtKodeBuku.setText(null);
        txtJudulBuku.setText(null);
        txtPengarang.setText(null);
        txtPenerbit.setText(null);
        txtTahunTerbit.setText(null);
        txtStok.setText(null);
        cbStatus.setSelectedItem("Tersedia");
        refresh();
        
        btnUbah.setEnabled(true);
        btnUbah.setEnabled(false);
        btnHapus.setEnabled(false);
    }
    
    public void idOtomatis()
    {
        String maxID = null;
        int idTampung = 0;
        String id = null;
        try
        {
            maxID = bukujpa.idMaxBuku();
        
            if (maxID != null)
            {
                //Substring digunakan untuk memecah string id_karyawan jadi KRY + 05
                //Substring(3, 2) maksudnya, mulai dari digit ke 3 (B = 0, K = 1, 0 = 2, 0 = 3) dan diambil 2 karakter (0 dan 5)
                //Kemudian di convert ke int, sehingga 5 + 1 = 6
                idTampung = Integer.parseInt(maxID.substring(3, 6))+1;
                //Jika idbrg nya kurang dari 10 maka "KRY0" + 6 = "KRY06"
                if (idTampung < 10)
                {
                    id = "BK000" + idTampung;
                }
                //Jika idbrg nya lebih dari sama dengan 10 dan kurang dari 100 (10 - 99) maka "KRY" + idbrg, idbrg = 10 jadi KRY10
                else if (idTampung >= 10 && idTampung < 100)
                {
                    id = "BK00" + idTampung;
                }
                else if(idTampung >= 100 && idTampung < 1000){
                    id = "BK0" + idTampung;
                }
            }
            //Jika maxid kosong berarti tidak ada data karyawan, maka id dimulai dari KRY01
            else
            {
                id = "BK0001";
            }  
        }
        catch(Exception e)
        {
             id = "BK0001";
        }
        txtKodeBuku.setText(id);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnMenuBuku = new javax.swing.JButton();
        btnMenuMember = new javax.swing.JButton();
        btnMenuPeminjaman = new javax.swing.JButton();
        btnMenuPengembalian = new javax.swing.JButton();
        btnMenuRiwayat = new javax.swing.JButton();
        btnMenuKeluar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtKodeBuku = new javax.swing.JTextField();
        txtJudulBuku = new javax.swing.JTextField();
        txtPengarang = new javax.swing.JTextField();
        txtStok = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtPenerbit = new javax.swing.JTextField();
        txtTahunTerbit = new javax.swing.JTextField();
        cbStatus = new javax.swing.JComboBox<>();
        btnSimpan = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBuku = new javax.swing.JTable();
        rbCariSemua = new javax.swing.JRadioButton();
        rbCariJudul = new javax.swing.JRadioButton();
        txtCariJudul = new javax.swing.JTextField();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 153, 153));

        jLabel15.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-literature-84.png"))); // NOI18N
        jLabel15.setText("Perpustakaan Kami");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(159, 159, 159))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        btnMenuBuku.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-read-32.png"))); // NOI18N
        btnMenuBuku.setText("Buku");
        btnMenuBuku.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        btnMenuMember.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-bank-cards-32.png"))); // NOI18N
        btnMenuMember.setText("Member");
        btnMenuMember.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnMenuMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuMemberActionPerformed(evt);
            }
        });

        btnMenuPeminjaman.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-book-shelf-32.png"))); // NOI18N
        btnMenuPeminjaman.setText("Peminjaman");
        btnMenuPeminjaman.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnMenuPeminjaman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuPeminjamanActionPerformed(evt);
            }
        });

        btnMenuPengembalian.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-checklist-32.png"))); // NOI18N
        btnMenuPengembalian.setText("Pengembalian");
        btnMenuPengembalian.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnMenuPengembalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuPengembalianActionPerformed(evt);
            }
        });

        btnMenuRiwayat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-report-card-32.png"))); // NOI18N
        btnMenuRiwayat.setText("Riwayat");
        btnMenuRiwayat.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnMenuRiwayat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuRiwayatActionPerformed(evt);
            }
        });

        btnMenuKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-logout-32.png"))); // NOI18N
        btnMenuKeluar.setText("Keluar");
        btnMenuKeluar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnMenuKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuKeluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMenuBuku, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMenuMember, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMenuPeminjaman, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMenuPengembalian, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMenuRiwayat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMenuKeluar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnMenuBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnMenuMember, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnMenuPeminjaman, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnMenuPengembalian, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnMenuRiwayat, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnMenuKeluar, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabel1.setText("Data Buku");

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder("Input Buku"));

        jLabel2.setText("ID Buku :");

        jLabel3.setText("Judul Buku :");

        jLabel4.setText("Pengarang :");

        jLabel5.setText("Stok :");

        jLabel6.setText("Penerbit :");

        jLabel7.setText("Tahun Terbit :");

        jLabel8.setText("Status :");

        cbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tersedia", "Kosong" }));

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnUbah.setText("Ubah");
        btnUbah.setEnabled(false);
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });

        btnHapus.setText("Hapus");
        btnHapus.setEnabled(false);
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnBatal.setText("Batal");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtKodeBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtJudulBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPengarang, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtStok, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(11, 11, 11)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPenerbit)
                            .addComponent(txtTahunTerbit)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(cbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUbah)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnHapus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBatal)
                        .addGap(11, 11, 11)))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtKodeBuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtPenerbit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtJudulBuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtTahunTerbit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtPengarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(cbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtStok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(22, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSimpan)
                            .addComponent(btnUbah)
                            .addComponent(btnHapus)
                            .addComponent(btnBatal))
                        .addContainerGap())))
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Daftar Buku"));

        tblBuku.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblBuku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBukuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblBuku);

        rbCariSemua.setText("Lihat Semua Buku");
        rbCariSemua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbCariSemuaActionPerformed(evt);
            }
        });

        rbCariJudul.setText("Lihat Berdasarkan Judul");
        rbCariJudul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbCariJudulActionPerformed(evt);
            }
        });

        txtCariJudul.setEnabled(false);
        txtCariJudul.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCariJudulKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(rbCariSemua)
                        .addGap(30, 30, 30)
                        .addComponent(rbCariJudul)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCariJudul, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbCariSemua)
                    .addComponent(rbCariJudul)
                    .addComponent(txtCariJudul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(257, 257, 257))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        TblBuku buku = new TblBuku();
        buku.setBkKd(txtKodeBuku.getText());
        buku.setBkJudul(txtJudulBuku.getText());
        buku.setBkPengarang(txtPengarang.getText());
        buku.setBkPenerbit(txtPenerbit.getText());
        buku.setBkTahunTerbit(txtTahunTerbit.getText());
        buku.setBkStok(Integer.valueOf(txtStok.getText()));
        buku.setBkStatus((String)cbStatus.getSelectedItem());
        
        try
        {
            bukujpa.simpanBuku(buku);
            JOptionPane.showMessageDialog(this, "Insert Data Buku Berhasil!");
        }
        catch(Exception e)
        {
            System.out.println("Error Saat Memanggil Method Simpan di Controller" +e);
        }
        
        refresh();
        clear();
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void rbCariSemuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbCariSemuaActionPerformed
        // TODO add your handling code here:
        tableModelBuku.deleteall();
        list = bukujpa.tampilSemua();
        for (TblBuku buku : list)
        {
            tableModelBuku.insert(buku);
        }
        txtCariJudul.setEnabled(false);
    }//GEN-LAST:event_rbCariSemuaActionPerformed

    private void rbCariJudulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbCariJudulActionPerformed
        // TODO add your handling code here:
        txtCariJudul.setEnabled(true);
    }//GEN-LAST:event_rbCariJudulActionPerformed

    private void tblBukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBukuMouseClicked
        // TODO add your handling code here:
        int i = tblBuku.getSelectedRow();
        if( i == -1)
        {
            return;
        }
        buku = tableModelBuku.select(i);
        txtKodeBuku.setText((String) tableModelBuku.getValueAt(i, 0));
        txtJudulBuku.setText((String) tableModelBuku.getValueAt(i, 1));
        txtPengarang.setText((String) tableModelBuku.getValueAt(i, 2));
        txtPenerbit.setText((String) tableModelBuku.getValueAt(i, 3));
        txtTahunTerbit.setText((String) tableModelBuku.getValueAt(i, 4));
        txtStok.setText(tableModelBuku.getValueAt(i, 5).toString());
        cbStatus.setSelectedItem(tableModelBuku.getValueAt(i, 6));
        
        btnUbah.setEnabled(false);
        btnUbah.setEnabled(true);
        btnHapus.setEnabled(true);
    }//GEN-LAST:event_tblBukuMouseClicked

    private void txtCariJudulKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariJudulKeyReleased
        // TODO add your handling code here:
        tableModelBuku.deleteall();
        list = bukujpa.tampilJudul("%" + txtCariJudul.getText() + "%");
        for (TblBuku buku : list)
        {
            tableModelBuku.insert(buku);
        }
    }//GEN-LAST:event_txtCariJudulKeyReleased

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        // TODO add your handling code here:
        int i = tblBuku.getSelectedRow();
        if(i == -1)
        {
            JOptionPane.showMessageDialog(null, "Pilih baris yang akan diubah!");
            return;
        }
        
        buku.setBkKd(txtKodeBuku.getText());
        buku.setBkJudul(txtJudulBuku.getText());
        buku.setBkPengarang(txtPengarang.getText());
        buku.setBkPenerbit(txtPenerbit.getText());
        buku.setBkTahunTerbit(txtTahunTerbit.getText());
        buku.setBkStok(Integer.valueOf(txtStok.getText()));
        buku.setBkStatus((String)cbStatus.getSelectedItem());
        
        try
        {
            bukujpa.editBuku(buku);
            JOptionPane.showMessageDialog(this, "Edit Data Buku Berhasil!");
        }
        catch(Exception e)
        {
            System.out.println("Error Saat Memanggil Method Edit di Controller" +e);
        }
        
        refresh();
        clear();
    }//GEN-LAST:event_btnUbahActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        int row = tblBuku.getSelectedRow();
        if(row != -1)
        {
            if(JOptionPane.showConfirmDialog(this, "Apakah anda yakin untuk menghapus data?", "Konfirmasi",
                    JOptionPane.YES_NO_OPTION) == JOptionPane.CANCEL_OPTION)
            {
                return;
            }
        }
        
        try
        {
            bukujpa.hapusBuku(list.get(row));
            JOptionPane.showMessageDialog(this, "Hapus Data Buku Berhasil!");
        }
        catch(Exception e)
        {
            System.out.println("Error Saat Memanggil Method Hapus di Controller" +e);
        }
        
        refresh();
        clear();
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_btnBatalActionPerformed

    private void btnMenuMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuMemberActionPerformed
        // TODO add your handling code here:
        member member = new member();
        this.setVisible(false);
        member.setVisible(true);
    }//GEN-LAST:event_btnMenuMemberActionPerformed

    private void btnMenuPeminjamanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuPeminjamanActionPerformed
        // TODO add your handling code here:
        peminjaman pinjam = new peminjaman();
        this.setVisible(false);
        pinjam.setVisible(true);
    }//GEN-LAST:event_btnMenuPeminjamanActionPerformed

    private void btnMenuPengembalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuPengembalianActionPerformed
        // TODO add your handling code here:
        pengembalian kembali = new pengembalian();
        this.setVisible(false);
        kembali.setVisible(true);
    }//GEN-LAST:event_btnMenuPengembalianActionPerformed

    private void btnMenuRiwayatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuRiwayatActionPerformed
        // TODO add your handling code here:
        riwayat_peminjaman riwayat = new riwayat_peminjaman();
        this.setVisible(false);
        riwayat.setVisible(true);
    }//GEN-LAST:event_btnMenuRiwayatActionPerformed

    private void btnMenuKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuKeluarActionPerformed
        // TODO add your handling code here:
        login login = new login();
        this.setVisible(false);
        login.setVisible(true);
    }//GEN-LAST:event_btnMenuKeluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(buku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(buku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(buku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(buku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new buku().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnMenuBuku;
    private javax.swing.JButton btnMenuKeluar;
    private javax.swing.JButton btnMenuMember;
    private javax.swing.JButton btnMenuPeminjaman;
    private javax.swing.JButton btnMenuPengembalian;
    private javax.swing.JButton btnMenuRiwayat;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnUbah;
    private javax.swing.JComboBox<String> cbStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbCariJudul;
    private javax.swing.JRadioButton rbCariSemua;
    private javax.swing.JTable tblBuku;
    private javax.swing.JTextField txtCariJudul;
    private javax.swing.JTextField txtJudulBuku;
    private javax.swing.JTextField txtKodeBuku;
    private javax.swing.JTextField txtPenerbit;
    private javax.swing.JTextField txtPengarang;
    private javax.swing.JTextField txtStok;
    private javax.swing.JTextField txtTahunTerbit;
    // End of variables declaration//GEN-END:variables
}
