/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.memberController;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import model.TableModelMember;
import model.TblMember;

/**
 *
 * @author User
 */
public class member extends javax.swing.JFrame {

    /**
     * Creates new form member
     */
    EntityManagerFactory emf = Persistence.createEntityManagerFactory("finalproject_team6PU");
    EntityManager em = emf.createEntityManager();
    memberController memberjpa = new memberController(em);
    List<TblMember> list = new ArrayList<TblMember>();
    private final TableModelMember tableModelMember;
    TblMember member = new TblMember();
    
    public member() {
        initComponents();
        tableModelMember = new TableModelMember();
        ButtonGroup group = new ButtonGroup();
        group.add(rbCariSemua);
        group.add(rbCariNama);
        tblMember.setModel(tableModelMember);
        list = memberjpa.tampilSemua();
        for (TblMember member : list)
        {
            tableModelMember.insert(member);
        }
        idOtomatis();
        txtKodeMember.setEditable(false);
    }
    
    private void refresh() {
        tableModelMember.deleteall();
        list = memberjpa.tampilSemua();
        for (TblMember member : list) {
            tableModelMember.insert(member);
        }
        rbCariSemua.setSelected(false);
        rbCariNama.setSelected(false);
        idOtomatis();
    }

    private void clear()
    {
        txtKodeMember.setText(null);
        txtNamaMember.setText(null);
        txtNoHP.setText(null);
        txtAlamat.setText(null);
        refresh();
        
        btnUbah.setEnabled(true);
        btnUbah.setEnabled(false);
        btnHapus.setEnabled(false);
    }
    
    public void idOtomatis()
    {
        String maxID = null;
        int idTampung = 0;
        String id = null;
        try
        {
            maxID = memberjpa.idMaxMember();
        
            if (maxID != null)
            {
                //Substring digunakan untuk memecah string id_karyawan jadi KRY + 05
                //Substring(3, 2) maksudnya, mulai dari digit ke 3 (B = 0, K = 1, 0 = 2, 0 = 3) dan diambil 2 karakter (0 dan 5)
                //Kemudian di convert ke int, sehingga 5 + 1 = 6
                idTampung = Integer.parseInt(maxID.substring(3, 6))+1;
                //Jika idbrg nya kurang dari 10 maka "KRY0" + 6 = "KRY06"
                if (idTampung < 10)
                {
                    id = "MB000" + idTampung;
                }
                //Jika idbrg nya lebih dari sama dengan 10 dan kurang dari 100 (10 - 99) maka "KRY" + idbrg, idbrg = 10 jadi KRY10
                else if (idTampung >= 10 && idTampung < 100)
                {
                    id = "MB00" + idTampung;
                }
                else if(idTampung >= 100 && idTampung < 1000){
                    id = "MB0" + idTampung;
                }
            }
            //Jika maxid kosong berarti tidak ada data karyawan, maka id dimulai dari KRY01
            else
            {
                id = "MB0001";
            }  
        }
        catch(Exception e)
        {
             id = "MB0001";
        }
        txtKodeMember.setText(id);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnMenuBuku = new javax.swing.JButton();
        btnMenuMember = new javax.swing.JButton();
        btnMenuPeminjaman = new javax.swing.JButton();
        btnMenuPengembalian = new javax.swing.JButton();
        btnMenuRiwayat = new javax.swing.JButton();
        btnMenuKeluar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtKodeMember = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNamaMember = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtNoHP = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAlamat = new javax.swing.JTextArea();
        btnSimpan = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblMember = new javax.swing.JTable();
        rbCariSemua = new javax.swing.JRadioButton();
        rbCariNama = new javax.swing.JRadioButton();
        txtCariNama = new javax.swing.JTextField();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 153, 153));

        jLabel11.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-literature-84.png"))); // NOI18N
        jLabel11.setText("Perpustakaan Kami");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(204, 204, 204)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        btnMenuBuku.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-read-32.png"))); // NOI18N
        btnMenuBuku.setText("Buku");
        btnMenuBuku.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnMenuBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuBukuActionPerformed(evt);
            }
        });

        btnMenuMember.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-bank-cards-32.png"))); // NOI18N
        btnMenuMember.setText("Member");
        btnMenuMember.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        btnMenuPeminjaman.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-book-shelf-32.png"))); // NOI18N
        btnMenuPeminjaman.setText("Peminjaman");
        btnMenuPeminjaman.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnMenuPeminjaman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuPeminjamanActionPerformed(evt);
            }
        });

        btnMenuPengembalian.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-checklist-32.png"))); // NOI18N
        btnMenuPengembalian.setText("Pengembalian");
        btnMenuPengembalian.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnMenuPengembalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuPengembalianActionPerformed(evt);
            }
        });

        btnMenuRiwayat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-report-card-32.png"))); // NOI18N
        btnMenuRiwayat.setText("Riwayat");
        btnMenuRiwayat.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnMenuRiwayat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuRiwayatActionPerformed(evt);
            }
        });

        btnMenuKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-logout-32.png"))); // NOI18N
        btnMenuKeluar.setText("Keluar");
        btnMenuKeluar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnMenuKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuKeluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMenuBuku, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMenuMember, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMenuPeminjaman, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMenuPengembalian, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMenuRiwayat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMenuKeluar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnMenuBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnMenuMember, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnMenuPeminjaman, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnMenuPengembalian, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnMenuRiwayat, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnMenuKeluar, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabel1.setText("Data Member");

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Input Member"));

        jLabel2.setText("ID Member : ");

        jLabel3.setText("Nama Member : ");

        jLabel4.setText("No. HP :");

        jLabel5.setText("Alamat : ");

        txtAlamat.setColumns(20);
        txtAlamat.setRows(5);
        jScrollPane1.setViewportView(txtAlamat);

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnUbah.setText("Ubah");
        btnUbah.setEnabled(false);
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });

        btnHapus.setText("Hapus");
        btnHapus.setEnabled(false);
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnBatal.setText("Batal");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtKodeMember, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNamaMember, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNoHP, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(btnSimpan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUbah)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnHapus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBatal)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtKodeMember, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtNoHP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(txtNamaMember, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimpan)
                    .addComponent(btnUbah)
                    .addComponent(btnHapus)
                    .addComponent(btnBatal))
                .addContainerGap())
        );

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder("Daftar Member"));

        tblMember.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblMember.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMemberMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblMember);

        rbCariSemua.setText("Lihat Semua Member");
        rbCariSemua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbCariSemuaActionPerformed(evt);
            }
        });

        rbCariNama.setText("Lihat Berdasarkan Nama");
        rbCariNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbCariNamaActionPerformed(evt);
            }
        });

        txtCariNama.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCariNamaKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(rbCariSemua)
                        .addGap(29, 29, 29)
                        .addComponent(rbCariNama)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCariNama, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbCariSemua)
                    .addComponent(rbCariNama)
                    .addComponent(txtCariNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(245, 245, 245)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        TblMember member = new TblMember();
        member.setMbKd(txtKodeMember.getText());
        member.setMbNama(txtNamaMember.getText());
        member.setMbNoHp(txtNoHP.getText());
        member.setMbAlamat(txtAlamat.getText());
        
        try
        {
            memberjpa.simpanMember(member);
            JOptionPane.showMessageDialog(this, "Insert Data Member Berhasil!");
        }
        catch(Exception e)
        {
            System.out.println("Error Saat Memanggil Method Simpan di Controller" +e);
        }
        
        refresh();
        clear();
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void rbCariSemuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbCariSemuaActionPerformed
        // TODO add your handling code here:
        tableModelMember.deleteall();
        list = memberjpa.tampilSemua();
        for (TblMember member : list)
        {
            tableModelMember.insert(member);
        }
        txtCariNama.setEnabled(false);
    }//GEN-LAST:event_rbCariSemuaActionPerformed

    private void rbCariNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbCariNamaActionPerformed
        // TODO add your handling code here:
        txtCariNama.setEnabled(true);
    }//GEN-LAST:event_rbCariNamaActionPerformed

    private void tblMemberMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMemberMouseClicked
        // TODO add your handling code here:
        int i = tblMember.getSelectedRow();
        if( i == -1)
        {
            return;
        }
        member = tableModelMember.select(i);
        txtKodeMember.setText((String) tableModelMember.getValueAt(i, 0));
        txtNamaMember.setText((String) tableModelMember.getValueAt(i, 1));
        txtNoHP.setText((String) tableModelMember.getValueAt(i, 2));
        txtAlamat.setText((String) tableModelMember.getValueAt(i, 3));
        
        btnUbah.setEnabled(false);
        btnUbah.setEnabled(true);
        btnHapus.setEnabled(true);
    }//GEN-LAST:event_tblMemberMouseClicked

    private void txtCariNamaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariNamaKeyReleased
        // TODO add your handling code here:
        tableModelMember.deleteall();
        list = memberjpa.tampilNama("%" + txtCariNama.getText() + "%");
        for (TblMember member : list)
        {
            tableModelMember.insert(member);
        }
    }//GEN-LAST:event_txtCariNamaKeyReleased

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        // TODO add your handling code here:
        int i = tblMember.getSelectedRow();
        if(i == -1)
        {
            JOptionPane.showMessageDialog(null, "Pilih baris yang akan diubah!");
            return;
        }
        
        member.setMbKd(txtKodeMember.getText());
        member.setMbNama(txtNamaMember.getText());
        member.setMbNoHp(txtNoHP.getText());
        member.setMbAlamat(txtAlamat.getText());
        
        try
        {
            memberjpa.editMember(member);
            JOptionPane.showMessageDialog(this, "Edit Data Member Berhasil!");
        }
        catch(Exception e)
        {
            System.out.println("Error Saat Memanggil Method Edit di Controller" +e);
        }
        
        refresh();
        clear();
    }//GEN-LAST:event_btnUbahActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        int row = tblMember.getSelectedRow();
        if(row != -1)
        {
            if(JOptionPane.showConfirmDialog(this, "Apakah anda yakin untuk menghapus data?", "Konfirmasi",
                    JOptionPane.YES_NO_OPTION) == JOptionPane.CANCEL_OPTION)
            {
                return;
            }
        }
        
        try
        {
            memberjpa.hapusMember(list.get(row));
            JOptionPane.showMessageDialog(this, "Hapus Data Member Berhasil!");
        }
        catch(Exception e)
        {
            System.out.println("Error Saat Memanggil Method Hapus di Controller" +e);
        }
        
        refresh();
        clear();
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_btnBatalActionPerformed

    private void btnMenuBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuBukuActionPerformed
        // TODO add your handling code here:
        buku buku = new buku();
        this.setVisible(false);
        buku.setVisible(true);
    }//GEN-LAST:event_btnMenuBukuActionPerformed

    private void btnMenuPeminjamanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuPeminjamanActionPerformed
        // TODO add your handling code here:
        peminjaman pinjam = new peminjaman();
        this.setVisible(false);
        pinjam.setVisible(true);
    }//GEN-LAST:event_btnMenuPeminjamanActionPerformed

    private void btnMenuPengembalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuPengembalianActionPerformed
        // TODO add your handling code here:
        pengembalian kembali = new pengembalian();
        this.setVisible(false);
        kembali.setVisible(true);
    }//GEN-LAST:event_btnMenuPengembalianActionPerformed

    private void btnMenuRiwayatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuRiwayatActionPerformed
        // TODO add your handling code here:
        riwayat_peminjaman riwayat = new riwayat_peminjaman();
        this.setVisible(false);
        riwayat.setVisible(true);
    }//GEN-LAST:event_btnMenuRiwayatActionPerformed

    private void btnMenuKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuKeluarActionPerformed
        // TODO add your handling code here:
        login login = new login();
        this.setVisible(false);
        login.setVisible(true);
    }//GEN-LAST:event_btnMenuKeluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(member.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(member.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(member.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(member.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new member().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnMenuBuku;
    private javax.swing.JButton btnMenuKeluar;
    private javax.swing.JButton btnMenuMember;
    private javax.swing.JButton btnMenuPeminjaman;
    private javax.swing.JButton btnMenuPengembalian;
    private javax.swing.JButton btnMenuRiwayat;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnUbah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JRadioButton rbCariNama;
    private javax.swing.JRadioButton rbCariSemua;
    private javax.swing.JTable tblMember;
    private javax.swing.JTextArea txtAlamat;
    private javax.swing.JTextField txtCariNama;
    private javax.swing.JTextField txtKodeMember;
    private javax.swing.JTextField txtNamaMember;
    private javax.swing.JTextField txtNoHP;
    // End of variables declaration//GEN-END:variables
}
