/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.peminjamanController;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import model.TableModelPeminjaman;
import model.TblTransaksi;

/**
 *
 * @author User
 */
public class riwayat_peminjaman extends javax.swing.JFrame {

    EntityManagerFactory emf = Persistence.createEntityManagerFactory("finalproject_team6PU");
    EntityManager em = emf.createEntityManager();
    peminjamanController peminjamanjpa = new peminjamanController(em);
    List<TblTransaksi> listPeminjaman = new ArrayList<TblTransaksi>();
    private TableModelPeminjaman tableModelPeminjaman;
    
    /**
     * Creates new form riwayat_peminjaman
     */
    public riwayat_peminjaman() {
        initComponents();
        load();
    }
    
    public void load(){
        tableModelPeminjaman = new TableModelPeminjaman();
        tblRiwayat.setModel(tableModelPeminjaman);
        tableModelPeminjaman.deleteall();
        tableModelPeminjaman.fireTableDataChanged();
        listPeminjaman = peminjamanjpa.tampilSemua();
        for (TblTransaksi peminjaman : listPeminjaman){
            tableModelPeminjaman.insert(peminjaman);
        }
        
        btnCari.setEnabled(false);
        rbCariStatus.setSelected(false);
        rbCariStatus.setEnabled(true);
        cbStatus.setSelectedIndex(0);
        cbStatus.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnMenuBuku = new javax.swing.JButton();
        btnMenuMember = new javax.swing.JButton();
        btnMenuPeminjaman = new javax.swing.JButton();
        btnMenuPengembalian = new javax.swing.JButton();
        btnMenuRiwayat = new javax.swing.JButton();
        btnMenuKeluar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRiwayat = new javax.swing.JTable();
        rbCariStatus = new javax.swing.JRadioButton();
        btnCari = new javax.swing.JButton();
        cbStatus = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 153, 153));

        jLabel8.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-literature-84.png"))); // NOI18N
        jLabel8.setText("Perpustakaan Kami");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(207, 207, 207))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        btnMenuBuku.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-read-32.png"))); // NOI18N
        btnMenuBuku.setText("Buku");
        btnMenuBuku.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnMenuBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuBukuActionPerformed(evt);
            }
        });

        btnMenuMember.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-bank-cards-32.png"))); // NOI18N
        btnMenuMember.setText("Member");
        btnMenuMember.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnMenuMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuMemberActionPerformed(evt);
            }
        });

        btnMenuPeminjaman.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-book-shelf-32.png"))); // NOI18N
        btnMenuPeminjaman.setText("Peminjaman");
        btnMenuPeminjaman.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnMenuPeminjaman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuPeminjamanActionPerformed(evt);
            }
        });

        btnMenuPengembalian.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-checklist-32.png"))); // NOI18N
        btnMenuPengembalian.setText("Pengembalian");
        btnMenuPengembalian.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnMenuPengembalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuPengembalianActionPerformed(evt);
            }
        });

        btnMenuRiwayat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-report-card-32.png"))); // NOI18N
        btnMenuRiwayat.setText("Riwayat");
        btnMenuRiwayat.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        btnMenuKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-logout-32.png"))); // NOI18N
        btnMenuKeluar.setText("Keluar");
        btnMenuKeluar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnMenuKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuKeluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMenuBuku, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMenuMember, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMenuPeminjaman, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMenuPengembalian, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMenuRiwayat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMenuKeluar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnMenuBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnMenuMember, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnMenuPeminjaman, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnMenuPengembalian, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnMenuRiwayat, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnMenuKeluar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabel1.setText("Riwayat Peminjaman");

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Data Riwayat Peminjaman"));

        tblRiwayat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblRiwayat);

        rbCariStatus.setText("Cari Berdasarkan Status : ");
        rbCariStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbCariStatusActionPerformed(evt);
            }
        });

        btnCari.setText("Cari");
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });

        cbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Semua", "Belum", "Sudah" }));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(rbCariStatus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63)
                        .addComponent(btnCari, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCari)
                    .addComponent(rbCariStatus)
                    .addComponent(cbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(215, 215, 215)
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 385, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbCariStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbCariStatusActionPerformed
        // TODO add your handling code here:
        cbStatus.setEnabled(true);
        btnCari.setEnabled(true);
    }//GEN-LAST:event_rbCariStatusActionPerformed

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        // TODO add your handling code here:
        String status_temp = (String)cbStatus.getSelectedItem();
        if(!status_temp.equals(null) || !status_temp.equals(""))
        {
            if(status_temp.equals("Semua"))
            {
                tableModelPeminjaman = new TableModelPeminjaman();
                tblRiwayat.setModel(tableModelPeminjaman);
                tableModelPeminjaman.deleteall();
                tableModelPeminjaman.fireTableDataChanged();
                listPeminjaman = peminjamanjpa.tampilSemua();
                for (TblTransaksi peminjaman : listPeminjaman){
                    tableModelPeminjaman.insert(peminjaman);
                }
            }
            else
            {
                tableModelPeminjaman = new TableModelPeminjaman();
                tblRiwayat.setModel(tableModelPeminjaman);
                tableModelPeminjaman.deleteall();
                tableModelPeminjaman.fireTableDataChanged();
                listPeminjaman = peminjamanjpa.tampilStatus((String)cbStatus.getSelectedItem());
                for (TblTransaksi peminjaman : listPeminjaman){
                    tableModelPeminjaman.insert(peminjaman);
                }
            }
            
        }
        else
        {
            load();
        }
    }//GEN-LAST:event_btnCariActionPerformed

    private void btnMenuKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuKeluarActionPerformed
        // TODO add your handling code here:
        login login = new login();
        this.setVisible(false);
        login.setVisible(true);
    }//GEN-LAST:event_btnMenuKeluarActionPerformed

    private void btnMenuBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuBukuActionPerformed
        // TODO add your handling code here:
        buku buku = new buku();
        this.setVisible(false);
        buku.setVisible(true);
    }//GEN-LAST:event_btnMenuBukuActionPerformed

    private void btnMenuMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuMemberActionPerformed
        // TODO add your handling code here:
        member member = new member();
        this.setVisible(false);
        member.setVisible(true);
    }//GEN-LAST:event_btnMenuMemberActionPerformed

    private void btnMenuPeminjamanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuPeminjamanActionPerformed
        // TODO add your handling code here:
        peminjaman pinjam = new peminjaman();
        this.setVisible(false);
        pinjam.setVisible(true);
    }//GEN-LAST:event_btnMenuPeminjamanActionPerformed

    private void btnMenuPengembalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuPengembalianActionPerformed
        // TODO add your handling code here:
        pengembalian kembali = new pengembalian();
        this.setVisible(false);
        kembali.setVisible(true);
    }//GEN-LAST:event_btnMenuPengembalianActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(riwayat_peminjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(riwayat_peminjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(riwayat_peminjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(riwayat_peminjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new riwayat_peminjaman().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnMenuBuku;
    private javax.swing.JButton btnMenuKeluar;
    private javax.swing.JButton btnMenuMember;
    private javax.swing.JButton btnMenuPeminjaman;
    private javax.swing.JButton btnMenuPengembalian;
    private javax.swing.JButton btnMenuRiwayat;
    private javax.swing.JComboBox<String> cbStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbCariStatus;
    private javax.swing.JTable tblRiwayat;
    // End of variables declaration//GEN-END:variables
}
